# Generated by Django 3.2.9 on 2021-11-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('article_content', models.TextField(verbose_name='Content')),
                ('article_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('amount_of_votes', models.IntegerField(default=0, verbose_name='Amount of votes')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('author_name', models.CharField(max_length=100, verbose_name='Author name')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='CommentAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Author name')),
                ('comment_content', models.TextField(verbose_name='Comment content')),
                ('comment_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsPage.articleabstract')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NewsPage.articleabstract')),
            ],
            bases=('NewsPage.articleabstract',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NewsPage.categoryabstract')),
            ],
            bases=('NewsPage.categoryabstract',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NewsPage.commentabstract')),
            ],
            bases=('NewsPage.commentabstract',),
        ),
        migrations.AddField(
            model_name='articleabstract',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsPage.categoryabstract', verbose_name='Category'),
        ),
    ]
